"""The public memory-layer leaderboard runner.

    OPENAI_API_KEY=sk-... python bench/leaderboard/run_board.py
    BOARD_SYSTEMS=memgram,memgram_v2,mem0,no-memory  BOARD_SEEDS=3  ... (defaults)

For every system x seed: ingest the persona conversations, then per question
measure  (a) recall correctness (LLM judge, temp 0),  (b) tokens injected per
retrieval,  (c) retrieval latency,  plus per-system time-to-queryable.
Systems whose adapter can't initialize (missing SDK / key / server) are
SKIPPED with the reason printed — the board never fails because one vendor
isn't installed.

Outputs: results_board.json (raw, per question) and LEADERBOARD.md (publishable,
with methodology + disclosure). Pin: package versions are recorded automatically.
"""
import importlib.metadata
import json
import os
import statistics
import sys
import time
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parent / "quality"))

from adapters import ADAPTERS as CORE_ADAPTERS  # noqa: E402
from adapters_ext import EXT_ADAPTERS  # noqa: E402
import run_eval  # noqa: E402  (reuses answer_from + judge: same protocol, same judge)

ALL = {**CORE_ADAPTERS, **EXT_ADAPTERS}
SYSTEMS = [s.strip() for s in os.environ.get(
    "BOARD_SYSTEMS", "memgram,memgram_v2,mem0,no-memory").split(",")]
SEEDS = int(os.environ.get("BOARD_SEEDS", "3"))
TOPK = int(os.environ.get("EVAL_TOPK", "6"))
TYPES = ["single", "update", "preference", "absent"]

VERSIONS = {}
for pkg in ("memgram", "mem0ai", "zep-cloud", "letta-client", "langmem", "openai"):
    try:
        VERSIONS[pkg] = importlib.metadata.version(pkg)
    except importlib.metadata.PackageNotFoundError:
        pass


def run_once(sys_name: str, cases: list) -> dict:
    adapter = ALL[sys_name]()
    rows, ret_lat, tok = [], [], []
    t_ingest0 = time.perf_counter()
    for case in cases:
        adapter.setup(case["persona"])
        for turns in case["sessions"]:
            adapter.ingest(case["persona"], turns)
    adapter.wait_ready()
    ttq = time.perf_counter() - t_ingest0
    for case in cases:
        for q in case["questions"]:
            t0 = time.perf_counter()
            mems = adapter.retrieve(case["persona"], q["q"], TOPK)
            ret_lat.append(time.perf_counter() - t0)
            tok.append(sum(len(m) for m in mems) // 4)
            pred = run_eval.answer_from(mems, q["q"])
            ok = run_eval.judge(q["q"], q["expect"], pred)
            rows.append({"persona": case["persona"], "type": q["type"], "q": q["q"],
                         "expect": q["expect"], "pred": pred, "ok": ok})
    return {"rows": rows, "time_to_queryable_s": round(ttq, 2),
            "retrieval_ms_p50": round(sorted(ret_lat)[len(ret_lat) // 2] * 1000, 1),
            "tokens_per_retrieval": round(statistics.mean(tok), 1)}


def aggregate(runs: list[dict]) -> dict:
    def scores(rows):
        by = defaultdict(lambda: [0, 0])
        for r in rows:
            by[r["type"]][0] += int(r["ok"]); by[r["type"]][1] += 1
        out = {t: (c / n * 100 if n else None) for t, (c, n) in by.items()}
        tot_c = sum(int(r["ok"]) for r in rows)
        out["overall"] = tot_c / len(rows) * 100
        return out
    per_seed = [scores(r["rows"]) for r in runs]
    agg = {}
    for key in ["overall"] + TYPES:
        vals = [s[key] for s in per_seed if s.get(key) is not None]
        if vals:
            agg[key] = {"mean": round(statistics.mean(vals), 1),
                        "min": round(min(vals), 1), "max": round(max(vals), 1)}
    agg["tokens_per_retrieval"] = round(statistics.mean(
        [r["tokens_per_retrieval"] for r in runs]), 1)
    agg["retrieval_ms_p50"] = round(statistics.mean(
        [r["retrieval_ms_p50"] for r in runs]), 1)
    agg["time_to_queryable_s"] = round(statistics.mean(
        [r["time_to_queryable_s"] for r in runs]), 1)
    return agg


def render_md(results: dict) -> str:
    ordered = sorted(results, key=lambda s: -results[s]["overall"]["mean"])
    lines = [
        "# Memory-Layer Leaderboard", "",
        f"Generated by [`bench/leaderboard/run_board.py`]"
        f"(run_board.py) — {SEEDS} seed(s) per system, top-k={TOPK}, "
        f"judge=`{run_eval.JUDGE_MODEL}` @ temp 0, answers from retrieved memories ONLY.", "",
        "> **Disclosure:** this board is published by the Memgram authors. The harness,",
        "> dataset, raw per-question results, and every adapter are in this repo —",
        "> rerun it yourself with one command. Corrections and adapter fixes for other",
        "> systems are very welcome (PRs).", "",
        "| System | Overall | Single | Update | Preference | Absent (abstain) | Tokens/query | Retrieval p50 | Time-to-queryable |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for s in ordered:
        a = results[s]
        def cell(k):
            v = a.get(k)
            if not v:
                return "—"
            spread = f" ({v['min']:.0f}–{v['max']:.0f})" if v["min"] != v["max"] else ""
            return f"{v['mean']:.1f}%{spread}"
        lines.append(
            f"| **{s}** | {cell('overall')} | {cell('single')} | {cell('update')} | "
            f"{cell('preference')} | {cell('absent')} | {a['tokens_per_retrieval']:.0f} | "
            f"{a['retrieval_ms_p50']:.0f} ms | {a['time_to_queryable_s']:.1f} s |")
    lines += [
        "", "## Methodology",
        "- Every system ingests the SAME multi-session persona conversations, then answers",
        "  the same questions **using only its retrieved memories** — the answer and judge",
        "  stages are shared code, so only memory quality differs.",
        "- `update` = a fact changed mid-history (latest must win). `absent` = never stated;",
        "  the correct answer is to abstain (hallucination resistance).",
        "- `no-memory` is the control: it re-stuffs the full transcript (max recall, max tokens).",
        "- Seeds rerun the full pipeline; spread shown as (min–max).",
        "", "## Pinned versions", "",
    ]
    lines += [f"- `{k}=={v}`" for k, v in sorted(VERSIONS.items())]
    lines += ["", "## Skipped systems", ""]
    for s, why in SKIPPED.items():
        lines.append(f"- `{s}`: {why}")
    if not SKIPPED:
        lines.append("(none)")
    return "\n".join(lines) + "\n"


SKIPPED: dict = {}


def main():
    if not os.environ.get("OPENAI_API_KEY"):
        sys.exit("Set OPENAI_API_KEY (answer+judge stages).")
    cases = json.loads((HERE.parent / "quality" / "dataset.json")
                       .read_text(encoding="utf-8"))["cases"]
    results = {}
    for s in SYSTEMS:
        if s not in ALL:
            SKIPPED[s] = "unknown system"
            continue
        try:
            ALL[s]()  # init probe: missing SDK/key/server -> skip loudly, not fatally
        except Exception as e:
            SKIPPED[s] = f"adapter init failed: {e}"
            print(f"SKIP {s}: {e}")
            continue
        print(f"\n=== {s}: {SEEDS} seed(s) ===")
        runs = []
        for seed in range(SEEDS):
            print(f"  seed {seed + 1}/{SEEDS} ...")
            runs.append(run_once(s, cases))
        results[s] = aggregate(runs)
        results[s]["_runs"] = runs

    (HERE / "results_board.json").write_text(
        json.dumps({"results": results, "versions": VERSIONS, "skipped": SKIPPED},
                   indent=2, default=str), encoding="utf-8")
    md = render_md(results)
    (HERE / "LEADERBOARD.md").write_text(md, encoding="utf-8")
    print("\n" + md)
    print("-> bench/leaderboard/LEADERBOARD.md  (+ results_board.json)")


if __name__ == "__main__":
    main()
